CREATE TABLE "roles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" varchar(30) NOT NULL,
	"name" varchar(80) NOT NULL,
	"description" text,
	"is_system" boolean DEFAULT true NOT NULL,
	"permissions" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "roles_code_uidx" UNIQUE("code")
);
--> statement-breakpoint
INSERT INTO "roles" ("code", "name", "description", "is_system", "permissions") VALUES ('teacher', '教师', '教师：负责本人学生/班级档案与家校沟通记录', true, '{"records":{"class":["view"],"student":["view","edit","inline_edit"],"guardian":["view","edit","inline_edit"],"communication":["view","edit","inline_edit","archive"],"guardian_communication":["view","edit","inline_edit","archive"],"student_event":["view","edit","archive"],"class_event":["view","edit","archive"],"student_case":["view"],"department":["view"],"user":["view"],"school":["view"],"referral":["view"],"audit":["view"],"import":["view"],"plan_operation":["view"],"access_request":["view"]},"pages":{"class":["view"],"student":["view","create"],"guardian":["view","create"],"communication":["view","create"],"guardian_communication":["view"],"student_event":["view","create"],"class_event":["view","create"],"student_case":["view"],"department":["view"],"user":["view"],"school":["view"],"referral":["view"],"audit":["view"],"import":["view"],"plan_operation":["view"],"access_request":["view"]}}'::jsonb) ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "roles" ("code", "name", "description", "is_system", "permissions") VALUES ('psychologist', '心理专员', '心理专员：仅转介工作台', true, '{"records":{"class":[],"student":[],"guardian":[],"communication":[],"guardian_communication":[],"student_event":[],"class_event":[],"student_case":[],"department":[],"user":[],"school":[],"referral":["view","edit"],"audit":[],"import":[],"plan_operation":[],"access_request":[]},"pages":{"class":[],"student":[],"guardian":[],"communication":[],"guardian_communication":[],"student_event":[],"class_event":[],"student_case":[],"department":[],"user":[],"school":[],"referral":["view"],"audit":[],"import":[],"plan_operation":[],"access_request":[]}}'::jsonb) ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "roles" ("code", "name", "description", "is_system", "permissions") VALUES ('school_admin', '学校管理员', '学校管理员：校内档案与账号生命周期管理', true, '{"records":{"class":["view","edit","archive","transfer","graduate","restore"],"student":["view","edit","archive","transfer","restore"],"guardian":["view","edit","archive","transfer","restore"],"communication":["view","edit","restore"],"guardian_communication":["view","edit","restore"],"student_event":["view","edit","restore"],"class_event":["view","edit","restore"],"student_case":["view","edit","restore"],"department":["view","edit","archive","restore"],"user":["view","edit","delete","disable"],"school":["view","edit","restore"],"referral":["view","transfer"],"audit":["view"],"import":["view"],"plan_operation":["view"],"access_request":["view"]},"pages":{"class":["view","create"],"student":["view","create"],"guardian":["view","create"],"communication":["view","create"],"guardian_communication":["view","create"],"student_event":["view","create"],"class_event":["view","create"],"student_case":["view","create"],"department":["view","create"],"user":["view","create"],"school":["view","create"],"referral":["view","create"],"audit":["view"],"import":["view"],"plan_operation":["view"],"access_request":["view"]}}'::jsonb) ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "roles" ("code", "name", "description", "is_system", "permissions") VALUES ('platform_admin', '平台管理员', '平台管理员：学校租户、账号与系统配置', true, '{"records":{"class":["view"],"student":["view"],"guardian":["view"],"communication":["view"],"guardian_communication":["view"],"student_event":["view"],"class_event":["view"],"student_case":["view"],"department":["view"],"user":["view","edit","delete","disable"],"school":["view","edit","restore"],"referral":["view","transfer"],"audit":["view"],"import":["view"],"plan_operation":["view"],"access_request":["view"]},"pages":{"class":["view"],"student":["view"],"guardian":["view"],"communication":["view"],"guardian_communication":["view"],"student_event":["view"],"class_event":["view"],"student_case":["view"],"department":["view"],"user":["view","create"],"school":["view","create"],"referral":["view"],"audit":["view"],"import":["view"],"plan_operation":["view"],"access_request":["view"]}}'::jsonb) ON CONFLICT ("code") DO NOTHING;
